version: "3.0"
services:
  qgis:
    build: docker
    volumes:
      - ./project:/project
      - ./html:/var/www/html
      - ./plugins:/qgis/plugins
    ports:
      - "8080:80"
    environment:
      QGIS_DEBUG: '1'
      QGIS_SERVER_LOG_FILE: '/tmp/qgis.log'
      QGIS_SERVER_LOG_LEVEL: "0"
      QGIS_PROJECT_FILE: /project/project-3.2.qgz


